version: "3.5"
services:
  datastore:
    image: singularities/datastore-emulator
    environment:
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
      DATASTORE_PROJECT_ID: virtual-power-plant-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 3s
      retries: 10
    ports:
      - 8081:8081
    build:
      context: .
      args:
        --no-store-on-disk:
    networks:
      - proxynet
networks:
  proxynet:
    name: datastore-network